import path from "node:path";
import type { PageSegment } from "./blocks.js";
import type { ScanResult } from "./scan.js";
import type { GitFacts } from "./git.js";
import type { FileSymbols } from "./symbols.js";
import { renderMermaid, type ModuleGraph } from "./graph.js";

export interface PageTemplate {
  /** Path relative to the wiki dir, e.g. "quickstart.md" or "modules/engine.md" */
  relPath: string;
  title: string;
  segments: PageSegment[];
}

export interface EmitInput {
  scan: ScanResult;
  git: GitFacts | null;
  symbols: Map<string, FileSymbols>;
  graph: ModuleGraph;
}

export function buildPages(input: EmitInput): PageTemplate[] {
  const modulePages = buildModulePages(input);

  return [
    buildQuickstart(input, modulePages),
    buildArchitecture(input),
    buildActivity(input),
    ...modulePages,
  ];
}

function raw(body: string): PageSegment {
  return { kind: "raw", body };
}

function facts(id: string, body: string, volatile = false): PageSegment {
  return {
    kind: "facts",
    id,
    body: `\n${body.trim()}\n`,
    ...(volatile ? { volatile: true } : {}),
  };
}

function prose(slot: string, hint: string): PageSegment {
  return {
    kind: "prose",
    slot,
    status: "empty",
    factsHash: "",
    hint,
    body: "\n",
  };
}

function projectName(scan: ScanResult): string {
  return (
    scan.manifests.find((manifest) => manifest.name)?.name ??
    path.basename(scan.root)
  );
}

/**
 * Every page of a scoped wiki states what its paths are relative to —
 * a module page read in isolation must not be mistaken for repo-root code.
 */
function scopeBanner(scan: ScanResult): string {
  return scan.scope
    ? `> Monorepo scope: all file paths on this page are relative to \`${scan.scope}/\`.\n\n`
    : "";
}

export function moduleSlug(moduleName: string): string {
  return moduleName
    .toLowerCase()
    .replace(/[^\w]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildQuickstart(
  input: EmitInput,
  modulePages: PageTemplate[],
): PageTemplate {
  const { scan, git } = input;
  const name = projectName(scan);
  const manifest = scan.manifests[0] ?? null;

  // The wiki lives at the repo root even when scoped to one monorepo app,
  // so links out of the wiki need the scope prefix.
  const sourcePrefix = scan.scope ? `../${scan.scope}/` : "../";

  const identity = [
    `- **Project:** ${name}`,
    scan.scope
      ? `- **Monorepo scope:** \`${scan.scope}/\` — this wiki documents only that app; file paths below are relative to it`
      : null,
    manifest?.description ? `- **Description:** ${manifest.description}` : null,
    `- **Languages:** ${
      scan.languages
        .slice(0, 6)
        .map((language) => `${language.name} (${language.files})`)
        .join(", ") || "none detected"
    }`,
    `- **Files:** ${scan.totalFiles} tracked, ${scan.codeFiles.length} source`,
    scan.readmes.length > 0
      ? `- **Existing docs:** ${scan.readmes
          .slice(0, 5)
          .map((readme) => `[${readme}](${sourcePrefix}${readme})`)
          .join(", ")}`
      : null,
  ]
    .filter(Boolean)
    .join("\n");

  // Changes on every commit — volatile so it never stales prose by itself.
  const gitState = git
    ? `- **Git:** branch \`${git.branch}\` at \`${git.head}\`${
        git.firstCommitDate ? `, first commit ${git.firstCommitDate}` : ""
      }`
    : `- **Git:** not a git repository`;

  const runLines: string[] = [];
  if (manifest && Object.keys(manifest.bin).length > 0) {
    runLines.push(
      `- **CLI binaries:** ${Object.entries(manifest.bin)
        .map(([binName, target]) => `\`${binName}\` → \`${target}\``)
        .join(", ")}`,
    );
  }
  if (manifest && Object.keys(manifest.scripts).length > 0) {
    runLines.push("- **Scripts:**");
    for (const [script, command] of Object.entries(manifest.scripts).slice(0, 12)) {
      runLines.push(`  - \`${script}\`: \`${command}\``);
    }
  }
  for (const other of scan.manifests.slice(manifest ? 1 : 0)) {
    runLines.push(`- **${other.kind} manifest:** \`${other.file}\``);
  }
  if (runLines.length === 0) {
    runLines.push("- No run scripts or binaries detected from manifests.");
  }

  const structureRows = modulePages
    .map((page) => {
      const moduleName = page.title.replace(/^Module: /, "");
      const module = input.graph.modules.get(moduleName);
      return `| [\`${moduleName}\`](${page.relPath}) | ${module?.files.length ?? 0} files |`;
    })
    .join("\n");

  const structure =
    modulePages.length > 0
      ? `| Module | Size |\n| --- | --- |\n${structureRows}`
      : "_No source modules detected._";

  return {
    relPath: "quickstart.md",
    title: `${name} — Quickstart`,
    segments: [
      raw(
        `# ${name} — Quickstart\n\n> Generated by [agentwiki](https://github.com/) — fact blocks are machine-maintained; prose sections are written by your coding agent.\n\n${scopeBanner(scan)}`,
      ),
      facts("identity", identity),
      raw(`\n`),
      facts("git-state", gitState, true),
      raw(`\n\n## What is this?\n\n`),
      prose(
        "what-is-this",
        "Explain in 2-3 paragraphs what this project is, who it is for, and why it exists. Use the identity facts and the repository README as sources.",
      ),
      raw(`\n\n## How to run it\n\n`),
      facts("run", runLines.join("\n")),
      raw(`\n\n`),
      prose(
        "getting-started-notes",
        "Describe the practical steps a new developer takes to install, run, and test this project locally, including anything surprising.",
      ),
      raw(`\n\n## Where things live\n\n`),
      facts("structure", structure),
      raw(
        `\n\nNext: [Architecture](architecture.md) · [Recent activity](activity.md)\n`,
      ),
    ],
  };
}

function buildArchitecture(input: EmitInput): PageTemplate {
  const { scan, graph } = input;
  const name = projectName(scan);

  const layout = scan.topDirs
    .filter((dir) => dir.name !== ".")
    .slice(0, 15)
    .map((dir) => `- \`${dir.name}/\` — ${dir.files} files (${dir.codeFiles} source)`)
    .join("\n");

  const entrypoints =
    scan.entrypoints.length > 0
      ? scan.entrypoints.map((entrypoint) => `- \`${entrypoint}\``).join("\n")
      : "- none detected";

  const mermaid = renderMermaid(graph);

  return {
    relPath: "architecture.md",
    title: `${name} — Architecture`,
    segments: [
      raw(
        `# Architecture\n\n[← Quickstart](quickstart.md)\n\n${scopeBanner(scan)}`,
      ),
      prose(
        "design-overview",
        "Explain the high-level architecture: the main runtime pieces, how data/control flows between the modules shown in the dependency graph, and the role of each entrypoint.",
      ),
      raw(`\n\n## Repository layout\n\n`),
      facts("layout", layout || "- flat repository, no top-level directories"),
      raw(`\n\n## Entrypoints\n\n`),
      facts("entrypoints", entrypoints),
      raw(`\n\n## Module dependency graph\n\n`),
      facts(
        "module-graph",
        mermaid ||
          "_No cross-module imports detected (single module or unsupported language)._",
      ),
      raw(`\n\n## Design decisions\n\n`),
      prose(
        "key-decisions",
        "Document notable design decisions and trade-offs visible in the code and git history (frameworks chosen, patterns used, things deliberately avoided).",
      ),
      raw(`\n`),
    ],
  };
}

function buildActivity(input: EmitInput): PageTemplate {
  const { scan, git } = input;
  const name = projectName(scan);

  const summary = git
    ? [
        `- **Branch:** \`${git.branch}\` at \`${git.head}\``,
        `- **Commits (last 90 days):** ${git.commitsRecent}`,
        `- **Active contributors (last 90 days):** ${git.contributorsRecent}`,
      ].join("\n")
    : "- Not a git repository — no history available.";

  const hotFiles =
    git && git.hotFiles.length > 0
      ? `| File | Commits (90d) |\n| --- | --- |\n${git.hotFiles
          .map((hot) => `| \`${hot.file}\` | ${hot.commits} |`)
          .join("\n")}`
      : "_No recent changes._";

  const recent =
    git && git.recentCommits.length > 0
      ? git.recentCommits
          .map(
            (commit) =>
              `- \`${commit.hash}\` ${commit.date} — ${commit.message} _(${commit.author})_`,
          )
          .join("\n")
      : "_No recent commits._";

  return {
    relPath: "activity.md",
    title: `${name} — Activity`,
    segments: [
      raw(
        `# Recent activity\n\n[← Quickstart](quickstart.md)\n\n${scopeBanner(scan)}`,
      ),
      facts("summary", summary),
      raw(`\n\n## Current focus\n\n`),
      prose(
        "current-focus",
        "Summarize what the team is currently working on, based on the hot files and recent commit messages below.",
      ),
      raw(`\n\n## Hot files\n\n`),
      facts("hot-files", hotFiles),
      raw(`\n\n## Recent commits\n\n`),
      facts("recent-commits", recent),
      raw(`\n`),
    ],
  };
}

const MIN_MODULE_FILES = 2;
const MAX_MODULE_PAGES = 48;
/** Sanity ceiling only — a component inventory should be complete. */
const MAX_MODULE_FILE_ROWS = 2000;

function buildModulePages(input: EmitInput): PageTemplate[] {
  const { scan, graph, symbols, git } = input;

  const modules = [...graph.modules.values()]
    .filter((module) => module.files.length >= MIN_MODULE_FILES)
    .sort((a, b) => b.files.length - a.files.length)
    .slice(0, MAX_MODULE_PAGES);

  return modules.map((module) => {
    const slug = moduleSlug(module.name);

    const fileRows = module.files
      .slice(0, MAX_MODULE_FILE_ROWS)
      .map((file) => {
        const fileSymbols = symbols.get(file);
        const exports = fileSymbols?.exports ?? [];
        const shown = exports.slice(0, 8).map((name) => `\`${name}\``).join(", ");
        const more = exports.length > 8 ? ` +${exports.length - 8} more` : "";
        return `| \`${file}\` | ${shown}${more || (exports.length === 0 ? "—" : "")} |`;
      })
      .join("\n");

    const files = `| File | Exports |\n| --- | --- |\n${fileRows}${
      module.files.length > MAX_MODULE_FILE_ROWS
        ? `\n| _…${module.files.length - MAX_MODULE_FILE_ROWS} more files_ | |`
        : ""
    }`;

    const importsTo = [...module.importsTo.entries()].sort((a, b) => b[1] - a[1]);
    const importedBy = [...module.importedBy.entries()].sort(
      (a, b) => b[1] - a[1],
    );

    const dependencies = [
      importsTo.length > 0
        ? `- **Imports from:** ${importsTo
            .map(([name, count]) => `\`${name}\` (${count})`)
            .join(", ")}`
        : "- **Imports from:** nothing internal",
      importedBy.length > 0
        ? `- **Imported by:** ${importedBy
            .map(([name, count]) => `\`${name}\` (${count})`)
            .join(", ")}`
        : "- **Imported by:** nothing internal",
    ].join("\n");

    const moduleHot = git
      ? git.hotFiles.filter((hot) =>
          module.files.some((file) => file === hot.file),
        )
      : [];
    const activity =
      moduleHot.length > 0
        ? moduleHot
            .map((hot) => `- \`${hot.file}\` — ${hot.commits} commits in 90d`)
            .join("\n")
        : "- No commits touched this module in the last 90 days.";

    return {
      relPath: `modules/${slug}.md`,
      title: `Module: ${module.name}`,
      segments: [
        raw(
          `# Module: \`${module.name}\`\n\n[← Quickstart](../quickstart.md) · [Architecture](../architecture.md)\n\n${scopeBanner(scan)}`,
        ),
        prose(
          "purpose",
          `Explain the purpose and responsibilities of the ${module.name} module: what it owns, its key abstractions, and how the rest of the codebase uses it.`,
        ),
        raw(`\n\n## Files and exports\n\n`),
        facts("files", files),
        raw(`\n\n## Dependencies\n\n`),
        facts("dependencies", dependencies),
        raw(`\n\n## Recent activity\n\n`),
        facts("activity", activity, true),
        raw(`\n\n## Notes for contributors\n\n`),
        prose(
          "notes",
          `Practical guidance for changing code in ${module.name}: invariants to respect, gotchas, and where tests live.`,
        ),
        raw(`\n`),
      ],
    };
  });
}
