import type { BackendId } from "./backends/types.js";
import { isBackendId } from "./backends/index.js";
import { VERSION } from "./constants.js";

export type Command =
  | { kind: "init" }
  | { kind: "update" }
  | { kind: "status" }
  | { kind: "doctor" }
  | { kind: "queue"; json: boolean }
  | { kind: "enrich"; backend: BackendId | null; dryRun: boolean }
  | { kind: "backend"; backend: BackendId | null }
  | { kind: "pause" }
  | { kind: "resume" }
  | { kind: "remove"; docs: boolean; yes: boolean }
  | { kind: "setup-action" }
  | { kind: "help" }
  | { kind: "version" }
  | { kind: "error"; message: string };

export function parseArgs(argv: string[]): Command {
  const [first, ...rest] = argv;

  if (!first || first === "help" || first === "--help" || first === "-h") {
    return { kind: "help" };
  }

  if (first === "version" || first === "--version" || first === "-v") {
    return { kind: "version" };
  }

  switch (first) {
    case "init":
      return { kind: "init" };
    case "update":
      return { kind: "update" };
    case "status":
      return { kind: "status" };
    case "doctor":
      return { kind: "doctor" };
    case "pause":
      return { kind: "pause" };
    case "resume":
      return { kind: "resume" };
    case "remove":
      return {
        kind: "remove",
        docs: rest.includes("--docs"),
        yes: rest.includes("--yes") || rest.includes("-y"),
      };
    case "setup-action":
      return { kind: "setup-action" };
    case "queue":
      return { kind: "queue", json: rest.includes("--json") };
    case "backend": {
      const value = rest.find((argument) => !argument.startsWith("-")) ?? null;
      if (value !== null && !isBackendId(value)) {
        return {
          kind: "error",
          message: `Unknown backend "${value}". Use: cursor | claude`,
        };
      }
      return { kind: "backend", backend: value };
    }
    case "enrich": {
      let backend: BackendId | null = null;
      const flagIndex = rest.indexOf("--backend");
      if (flagIndex !== -1) {
        const value = rest[flagIndex + 1];
        if (!value || !isBackendId(value)) {
          return {
            kind: "error",
            message: `--backend requires a value: cursor | claude`,
          };
        }
        backend = value;
      }
      return { kind: "enrich", backend, dryRun: rest.includes("--dry-run") };
    }
    default:
      return { kind: "error", message: `Unknown command: ${first}` };
  }
}

export const HELP_TEXT = `agentwiki v${VERSION} — deterministic codebase wiki, prose by the agent you already have

Usage
  agentwiki <command> [options]

Commands
  init                  Generate the wiki and wire agent integrations
  update                Refresh fact blocks from the current code & git state
  status                Show wiki freshness and backend readiness
  queue [--json]        List prose slots that need writing (empty or stale)
  enrich                Have your coding agent write the queued prose slots
    --backend <id>        cursor | claude (overrides saved preference)
    --dry-run             Print the prompt that would be sent, run nothing
  backend [<id>]        Show or save the preferred backend (cursor | claude)
  pause                 Pause agentwiki: detach Cursor hook & rule, updates
                        become no-ops — all docs are kept
  resume                Re-enable a paused setup
  remove [--docs] [-y]  Remove all agentwiki integrations (asks to confirm).
                        Docs in agentwiki/ are KEPT unless --docs is passed
  setup-action          Write the GitHub Actions workflow template
  doctor                Check environment: git, backends, auth, wiki state
  help, version

How it works
  Wiki pages under agentwiki/ mix machine-owned fact blocks (regenerated by
  init/update, never hand-edited) with prose slots owned by your coding agent.
  'queue' lists slots whose facts changed; 'enrich' asks Cursor CLI or Claude
  Code — on your existing subscription, no extra API keys — to write them.

Examples
  agentwiki init
  agentwiki queue --json
  agentwiki enrich --backend cursor
  agentwiki backend claude
`;
